//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 10:07:32 PM SGT 
//


package weatherdata.data.taf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}cloud_coverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}cloud_base_ft" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}cloud_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cloudCoverage",
    "cloudBaseFt",
    "cloudType"
})
@XmlRootElement(name = "cloud")
public class Cloud {

    @XmlElement(name = "cloud_coverage")
    protected List<String> cloudCoverage;
    @XmlElement(name = "cloud_base_ft", type = Integer.class)
    protected List<Integer> cloudBaseFt;
    @XmlElement(name = "cloud_type")
    protected List<String> cloudType;

    /**
     * Gets the value of the cloudCoverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cloudCoverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCloudCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCloudCoverage() {
        if (cloudCoverage == null) {
            cloudCoverage = new ArrayList<String>();
        }
        return this.cloudCoverage;
    }

    /**
     * Gets the value of the cloudBaseFt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cloudBaseFt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCloudBaseFt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getCloudBaseFt() {
        if (cloudBaseFt == null) {
            cloudBaseFt = new ArrayList<Integer>();
        }
        return this.cloudBaseFt;
    }

    /**
     * Gets the value of the cloudType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cloudType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCloudType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCloudType() {
        if (cloudType == null) {
            cloudType = new ArrayList<String>();
        }
        return this.cloudType;
    }

}
