//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 10:07:32 PM SGT 
//


package weatherdata.data.taf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fcst_time_from" minOccurs="0"/>
 *         &lt;element ref="{}fcst_time_to" minOccurs="0"/>
 *         &lt;element ref="{}change_indicator" minOccurs="0"/>
 *         &lt;element ref="{}time_becoming" minOccurs="0"/>
 *         &lt;element ref="{}probability" minOccurs="0"/>
 *         &lt;element ref="{}wind_dir_degrees" minOccurs="0"/>
 *         &lt;element ref="{}wind_speed_kt" minOccurs="0"/>
 *         &lt;element ref="{}wind_gust_kt" minOccurs="0"/>
 *         &lt;element ref="{}wind_shear_hgt_ft" minOccurs="0"/>
 *         &lt;element ref="{}wind_shear_dir_degrees" minOccurs="0"/>
 *         &lt;element ref="{}wind_shear_speed_kt" minOccurs="0"/>
 *         &lt;element ref="{}visibility_mi" minOccurs="0"/>
 *         &lt;element ref="{}altim_mb" minOccurs="0"/>
 *         &lt;element ref="{}vert_vis_ft" minOccurs="0"/>
 *         &lt;element ref="{}wx_string" minOccurs="0"/>
 *         &lt;element ref="{}not_decoded" minOccurs="0"/>
 *         &lt;element ref="{}cloud" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}turbulence" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}icing" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}temperature" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fcstTimeFrom",
    "fcstTimeTo",
    "changeIndicator",
    "timeBecoming",
    "probability",
    "windDirDegrees",
    "windSpeedKt",
    "windGustKt",
    "windShearHgtFt",
    "windShearDirDegrees",
    "windShearSpeedKt",
    "visibilityMi",
    "altimMb",
    "vertVisFt",
    "wxString",
    "notDecoded",
    "cloud",
    "turbulence",
    "icing",
    "temperature"
})
@XmlRootElement(name = "forecast")
public class Forecast {

    @XmlElement(name = "fcst_time_from")
    protected Integer fcstTimeFrom;
    @XmlElement(name = "fcst_time_to")
    protected Integer fcstTimeTo;
    @XmlElement(name = "change_indicator")
    protected String changeIndicator;
    @XmlElement(name = "time_becoming")
    protected String timeBecoming;
    protected Integer probability;
    @XmlElement(name = "wind_dir_degrees")
    protected Short windDirDegrees;
    @XmlElement(name = "wind_speed_kt")
    protected Integer windSpeedKt;
    @XmlElement(name = "wind_gust_kt")
    protected Integer windGustKt;
    @XmlElement(name = "wind_shear_hgt_ft")
    protected Short windShearHgtFt;
    @XmlElement(name = "wind_shear_dir_degrees")
    protected Short windShearDirDegrees;
    @XmlElement(name = "wind_shear_speed_kt")
    protected Integer windShearSpeedKt;
    @XmlElement(name = "visibility_mi")
    protected Float visibilityMi;
    @XmlElement(name = "altim_mb")
    protected Short altimMb;
    @XmlElement(name = "vert_vis_ft")
    protected Short vertVisFt;
    @XmlElement(name = "wx_string")
    protected String wxString;
    @XmlElement(name = "not_decoded")
    protected String notDecoded;
    protected List<Cloud> cloud;
    protected List<Turbulence> turbulence;
    protected List<Icing> icing;
    protected List<Temperature> temperature;

    /**
     * Gets the value of the fcstTimeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFcstTimeFrom() {
        return fcstTimeFrom;
    }

    /**
     * Sets the value of the fcstTimeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFcstTimeFrom(Integer value) {
        this.fcstTimeFrom = value;
    }

    /**
     * Gets the value of the fcstTimeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFcstTimeTo() {
        return fcstTimeTo;
    }

    /**
     * Sets the value of the fcstTimeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFcstTimeTo(Integer value) {
        this.fcstTimeTo = value;
    }

    /**
     * Gets the value of the changeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeIndicator() {
        return changeIndicator;
    }

    /**
     * Sets the value of the changeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeIndicator(String value) {
        this.changeIndicator = value;
    }

    /**
     * Gets the value of the timeBecoming property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeBecoming() {
        return timeBecoming;
    }

    /**
     * Sets the value of the timeBecoming property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeBecoming(String value) {
        this.timeBecoming = value;
    }

    /**
     * Gets the value of the probability property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProbability() {
        return probability;
    }

    /**
     * Sets the value of the probability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProbability(Integer value) {
        this.probability = value;
    }

    /**
     * Gets the value of the windDirDegrees property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getWindDirDegrees() {
        return windDirDegrees;
    }

    /**
     * Sets the value of the windDirDegrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setWindDirDegrees(Short value) {
        this.windDirDegrees = value;
    }

    /**
     * Gets the value of the windSpeedKt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWindSpeedKt() {
        return windSpeedKt;
    }

    /**
     * Sets the value of the windSpeedKt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindSpeedKt(Integer value) {
        this.windSpeedKt = value;
    }

    /**
     * Gets the value of the windGustKt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWindGustKt() {
        return windGustKt;
    }

    /**
     * Sets the value of the windGustKt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindGustKt(Integer value) {
        this.windGustKt = value;
    }

    /**
     * Gets the value of the windShearHgtFt property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getWindShearHgtFt() {
        return windShearHgtFt;
    }

    /**
     * Sets the value of the windShearHgtFt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setWindShearHgtFt(Short value) {
        this.windShearHgtFt = value;
    }

    /**
     * Gets the value of the windShearDirDegrees property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getWindShearDirDegrees() {
        return windShearDirDegrees;
    }

    /**
     * Sets the value of the windShearDirDegrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setWindShearDirDegrees(Short value) {
        this.windShearDirDegrees = value;
    }

    /**
     * Gets the value of the windShearSpeedKt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWindShearSpeedKt() {
        return windShearSpeedKt;
    }

    /**
     * Sets the value of the windShearSpeedKt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindShearSpeedKt(Integer value) {
        this.windShearSpeedKt = value;
    }

    /**
     * Gets the value of the visibilityMi property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVisibilityMi() {
        return visibilityMi;
    }

    /**
     * Sets the value of the visibilityMi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVisibilityMi(Float value) {
        this.visibilityMi = value;
    }

    /**
     * Gets the value of the altimMb property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAltimMb() {
        return altimMb;
    }

    /**
     * Sets the value of the altimMb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAltimMb(Short value) {
        this.altimMb = value;
    }

    /**
     * Gets the value of the vertVisFt property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getVertVisFt() {
        return vertVisFt;
    }

    /**
     * Sets the value of the vertVisFt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setVertVisFt(Short value) {
        this.vertVisFt = value;
    }

    /**
     * Gets the value of the wxString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWxString() {
        return wxString;
    }

    /**
     * Sets the value of the wxString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWxString(String value) {
        this.wxString = value;
    }

    /**
     * Gets the value of the notDecoded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotDecoded() {
        return notDecoded;
    }

    /**
     * Sets the value of the notDecoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotDecoded(String value) {
        this.notDecoded = value;
    }

    /**
     * Gets the value of the cloud property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cloud property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCloud().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cloud }
     * 
     * 
     */
    public List<Cloud> getCloud() {
        if (cloud == null) {
            cloud = new ArrayList<Cloud>();
        }
        return this.cloud;
    }

    /**
     * Gets the value of the turbulence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the turbulence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTurbulence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Turbulence }
     * 
     * 
     */
    public List<Turbulence> getTurbulence() {
        if (turbulence == null) {
            turbulence = new ArrayList<Turbulence>();
        }
        return this.turbulence;
    }

    /**
     * Gets the value of the icing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Icing }
     * 
     * 
     */
    public List<Icing> getIcing() {
        if (icing == null) {
            icing = new ArrayList<Icing>();
        }
        return this.icing;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the temperature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemperature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Temperature }
     * 
     * 
     */
    public List<Temperature> getTemperature() {
        if (temperature == null) {
            temperature = new ArrayList<Temperature>();
        }
        return this.temperature;
    }

}
