//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 10:07:32 PM SGT 
//


package weatherdata.data.taf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}icing_intensity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}icing_min_alt_mb" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}icing_max_alt_mb" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "icingIntensity",
    "icingMinAltMb",
    "icingMaxAltMb"
})
@XmlRootElement(name = "icing")
public class Icing {

    @XmlElement(name = "icing_intensity")
    protected List<String> icingIntensity;
    @XmlElement(name = "icing_min_alt_mb", type = Integer.class)
    protected List<Integer> icingMinAltMb;
    @XmlElement(name = "icing_max_alt_mb", type = Integer.class)
    protected List<Integer> icingMaxAltMb;

    /**
     * Gets the value of the icingIntensity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icingIntensity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcingIntensity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIcingIntensity() {
        if (icingIntensity == null) {
            icingIntensity = new ArrayList<String>();
        }
        return this.icingIntensity;
    }

    /**
     * Gets the value of the icingMinAltMb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icingMinAltMb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcingMinAltMb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getIcingMinAltMb() {
        if (icingMinAltMb == null) {
            icingMinAltMb = new ArrayList<Integer>();
        }
        return this.icingMinAltMb;
    }

    /**
     * Gets the value of the icingMaxAltMb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icingMaxAltMb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcingMaxAltMb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getIcingMaxAltMb() {
        if (icingMaxAltMb == null) {
            icingMaxAltMb = new ArrayList<Integer>();
        }
        return this.icingMaxAltMb;
    }

}
