//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 10:07:32 PM SGT 
//


package weatherdata.data.taf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}valid_time" minOccurs="0"/>
 *         &lt;element ref="{}sfc_temp_c" minOccurs="0"/>
 *         &lt;element ref="{}max_or_min" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validTime",
    "sfcTempC",
    "maxOrMin"
})
@XmlRootElement(name = "temperature")
public class Temperature {

    @XmlElement(name = "valid_time")
    protected Integer validTime;
    @XmlElement(name = "sfc_temp_c")
    protected Float sfcTempC;
    @XmlElement(name = "max_or_min")
    protected String maxOrMin;

    /**
     * Gets the value of the validTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValidTime() {
        return validTime;
    }

    /**
     * Sets the value of the validTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValidTime(Integer value) {
        this.validTime = value;
    }

    /**
     * Gets the value of the sfcTempC property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSfcTempC() {
        return sfcTempC;
    }

    /**
     * Sets the value of the sfcTempC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSfcTempC(Float value) {
        this.sfcTempC = value;
    }

    /**
     * Gets the value of the maxOrMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxOrMin() {
        return maxOrMin;
    }

    /**
     * Sets the value of the maxOrMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxOrMin(String value) {
        this.maxOrMin = value;
    }

}
