//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 10:07:32 PM SGT 
//


package weatherdata.data.taf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}turbulence_intensity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}turbulence_min_alt_mb" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}turbulence_max_alt_mb" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "turbulenceIntensity",
    "turbulenceMinAltMb",
    "turbulenceMaxAltMb"
})
@XmlRootElement(name = "turbulence")
public class Turbulence {

    @XmlElement(name = "turbulence_intensity")
    protected List<String> turbulenceIntensity;
    @XmlElement(name = "turbulence_min_alt_mb", type = Integer.class)
    protected List<Integer> turbulenceMinAltMb;
    @XmlElement(name = "turbulence_max_alt_mb", type = Integer.class)
    protected List<Integer> turbulenceMaxAltMb;

    /**
     * Gets the value of the turbulenceIntensity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the turbulenceIntensity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTurbulenceIntensity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTurbulenceIntensity() {
        if (turbulenceIntensity == null) {
            turbulenceIntensity = new ArrayList<String>();
        }
        return this.turbulenceIntensity;
    }

    /**
     * Gets the value of the turbulenceMinAltMb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the turbulenceMinAltMb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTurbulenceMinAltMb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getTurbulenceMinAltMb() {
        if (turbulenceMinAltMb == null) {
            turbulenceMinAltMb = new ArrayList<Integer>();
        }
        return this.turbulenceMinAltMb;
    }

    /**
     * Gets the value of the turbulenceMaxAltMb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the turbulenceMaxAltMb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTurbulenceMaxAltMb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getTurbulenceMaxAltMb() {
        if (turbulenceMaxAltMb == null) {
            turbulenceMaxAltMb = new ArrayList<Integer>();
        }
        return this.turbulenceMaxAltMb;
    }

}
